AWSTemplateFormatVersion: "2010-09-09"
Description: Callen ensimmäinen PilviMuotoilu
Parameters:
  LatestAmiId:
    Type: 'AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>'
    Default: '/aws/service/ami-amazon-linux-latest/amzn2-ami-hvm-x86_64-gp2'
Resources:
  CallenS3: 
    Type: AWS::S3::Bucket
    Properties: 
      BucketName: callepilviformaatios3
  CallenYono:
    Type: AWS::SQS::Queue
    Properties: 
      QueueName: YonoCallen
  CallenEC2:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !Ref LatestAmiId
      InstanceType: t3.nano
      #Name: CallenEC2
  CallenLB:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties: 
      Name: CallenLB
      Scheme: internet-facing
      Subnets: 
      - subnet-0deb6257
      - subnet-1629765e
      - subnet-7b95d91d

 