AWSTemplateFormatVersion: "2010-09-09"
Description: Callen ensimmäinen PilviMuotoilu
Resources:
  CallenS3: 
    Type: AWS::S3::Bucket
    Properties: 
      BucketName: callepilviformaatios3
  CallenYono:
    Type: AWS::SQS::Queue
    Properties: 
      QueueName: YonoCallen
 